stages:
  - build

build_and_run_podman:
  stage: build
  script:
    - git pull origin main
    - podman stop stats_methods || true
    - podman rm stats_methods || true
    - podman image build -t stats_methods_image .
    - podman run -d --name stats_methods -p 8054:8000 --network bridge stats_methods_image
  only:
    - main
